package RBT;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.security.MessageDigest;
import java.util.Arrays;
import java.util.Comparator;
import java.util.Map;
import java.util.TreeMap;
import java.util.concurrent.ThreadLocalRandom;
import org.msgpack.core.MessagePack;
import org.msgpack.core.MessagePacker;
import org.msgpack.core.MessageUnpacker;

/**
 * Loads or generates a rainbow table, given expected parameters in <code>Config</code> object.
 * Also contains static <code>Table</code> helper functions.
 *
 * @see Config
 * @see Search
 * @author Chris Cameron
 */
public class Table {

  /** Displays extra table generation data. */
  final static boolean DEBUG = true;

  // Rainbow table chains to be populated
  /**
   * <code>TreeMap</code> of plain-text keys to hashes in <code>byte[]</code> form.
   * @see java.util.TreeMap
   */
  protected Map<String, byte[]> keyToHash = new TreeMap<>();
  /**
   * <code>TreeMap</code> of hashes in <code>byte[]</code> form to plain-text keys.
   * @see java.util.TreeMap
   */
  protected Map<byte[], String> hashToKey = new TreeMap<>(new ByteArrayComparator());

//  public static final Character[] ALLOWABLE_CHARS = {
//      'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's',
//      't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L',
//      'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'
//  };
  /** Allowable characters in the plain-text key space. */
  public static final Character[] ALLOWABLE_CHARS = {
      'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's',
      't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'
  };
//  public static final Character[] ALLOWABLE_CHARS = {
//      'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's',
//      't', 'u', 'v', 'w', 'x', 'y', 'z'
//  };
  /** Length of the hash generated by the hashing algorithm (SHA-1). */
  public static final int HASHLEN = 40;

  /* CONFIGURATION */
  /** Simple name for a default parameter from <code>Config</code> object. */
  public int keyLength;
  /** Simple name for a default parameter from <code>Config</code> object. */
  public int chainLength;
  /** Simple name for a default parameter from <code>Config</code> object. */
  public long tableLength;
  /**
   * A count of all possible keys, given <code>keyLength</code> and <code>ALLOWABLE_CHARS</code>.
   * @see #keyLength
   * @see #ALLOWABLE_CHARS
   * */
  public long keySpace;
  /** Location of the serialized <code>TreeMap</code> tables. */
  public String fileName;

  /**
   * <code>Comparator</code> for <code>byte[]</code>. This allows hashes in the form of
   * <code>byte[]</code> to be used as <code>TreeMap</code> keys.<br>
   * Credit to: https://stackoverflow.com/a/38552674/3846437
   * @see Comparator
   */
  static class ByteArrayComparator implements Comparator<byte[]> {
    @Override
    public int compare(byte[] o1, byte[] o2) {
      int result = 0;
      int maxLength = Math.max(o1.length, o2.length);
      for (int index = 0; index < maxLength; index++) {
        byte o1Value = index < o1.length ? o1[index] : 0;
        byte o2Value = index < o2.length ? o2[index] : 0;
        int cmp     = Byte.compare(o1Value, o2Value);
        if (cmp != 0) {
          result = cmp;
          break;
        }
      }
      return result;
    }
  }

  /**
   * Constructs a rainbow table using parameters from <code>cfg</code>.
   * @param cfg Configuration parameters
   */
  Table(Config cfg) {
    keyLength = cfg.getKeyLen();
    chainLength = cfg.getChainLen();
    tableLength = cfg.getTblLen();
    keySpace = (long) Math.pow(ALLOWABLE_CHARS.length, keyLength);

    /*
     * Generate the file name a previously generated rainbow table would have
     * used, given the parameters set. May or may not exist.
     */
    // Create a string of configuration parameters, and hash that string for file name
    String cfgString =
        Arrays.deepToString(ALLOWABLE_CHARS)
            + keyLength
            + chainLength
            + tableLength;
    fileName = "RT_" + cfgString.hashCode() + ".ser";

    // If computed hash tables aren't on disk, compute them
    if (!loadHashMap()) {
      createTable(tableLength);
      writeHashMap();
    }
  }

  /* PUBLIC */
  /** Prints table information summary. */
  public void printSummary() {
    System.out.println("Rainbow table loaded with the following parameters:");
    System.out.println("  Configured -");
    System.out.printf("    * %13s: %,d%n", "Table length", hashToKey.size());
    System.out.printf("    * %13s: %,d%n", "Chain length", chainLength);
    System.out.printf("    * %13s: %,d%n", "Key length", keyLength);
    System.out.println();
    System.out.println("  Static -");
    System.out.printf("    * %13s: %,d%n", "Key space size", keySpace);
    System.out.printf("    * %13s:%n", "Allowable character set");
    // TODO: I know this output looks bad, but it appears the effort to wrap the output is more
    // trouble than I think it's worth right now.
    System.out.println(Arrays.deepToString(ALLOWABLE_CHARS));
    System.out.println();
  }


  /* PROTECTED */
  /**
   * Converts a byte array to hex for familiar looking SHA-1 hashes.<br>
   * Credit to: https://stackoverflow.com/a/311179/3846437
   * @param b byte[] of length 20
   * @return Hex string of 40-characters
   */
  protected static String byteArrayToHexString(byte[] b) {
    String result = "";
    for (int i = 0; i < b.length; i++) {
      result += Integer.toString((b[i] & 0xff) + 0x100, 16).substring(1);
    }
    return result;
  }

  /**
   * Converts a hex string representing an SHA-1 hash to a <code>byte[]</code>.
   * This is compatible with what {@link java.security.MessageDigest#digest()} returns.
   * @see MessageDigest#digest()
   * @param s Hex string of 40-characters
   * @return byte[] of length 20
   */
  protected static byte[] hexStringToByteArray(String s) {
    byte[] result = new byte[(s.length()/2)];
    int front = 0;
    int back = 2;
    for(int i = 0; i < (s.length()/2); i++) {
      String hex = s.substring(front, back);
      result[i] = (byte)Integer.parseInt(hex, 16);
      front = back;
      back += 2;
    }

    return result;
  }

  /**
   * Creates an SHA-1 hash of supplied string in <code>byte[]</code> form.
   * Uses {@link java.security.MessageDigest#digest()}.
   * @see java.security.MessageDigest#digest()
   * @param plaintext String to hash
   * @return byte[] of length 20
   */
  protected static byte[] createShaHash(String plaintext) {
    MessageDigest shaHash = null;
    try {
      shaHash = MessageDigest.getInstance("SHA-1");
    } catch (Exception e) {
      System.out.println(e);
      System.exit(-1);
    }
    shaHash.update(plaintext.getBytes());

    return shaHash.digest();
  }

  /**
   * Create a rainbow table of length <code>num</code>.
   * @param num Length of table generated
   */
  protected void createTable(long num) {
    System.out.format("Generating table of size %,d%n", num);
    System.out.format("%s\t%s\t%s\t%s\t%s%n",
        "Elapsed", "Rows remaining", "Rows complete/time", "Collisions", "Successful H/s");
    long startTime = System.currentTimeMillis() / 1000L;
    long execTime = System.currentTimeMillis() / 1000L;
    long printTime = 30; // Print every 30 seconds
    int collisions = 0; // Number of key collisions
    int prevCollisions = 0;
    long prevNum = num; // The value of 'num' at the previous time of reporting.
    while (num > 0) {
      if( ((System.currentTimeMillis() / 1000L)-execTime) >= printTime && DEBUG) {
        System.out.format("%d\t%d\t%d\t%d\t%d%n",
            System.currentTimeMillis()/1000L - startTime,
            num,
            prevNum-num,
            collisions-prevCollisions,
            (prevNum-num)*chainLength/(System.currentTimeMillis()/1000L - execTime));
        execTime = System.currentTimeMillis()/1000L;
        prevCollisions = collisions;
        prevNum = num;
      }
      String key = generateKey(); // Starting chain key
      byte[] hash = hashReduceStep(createShaHash(key), (chainLength - 1));

      // If the hash already exists in hashToKey, generate a new chain
      // I believe we should only collide here if two different
      // starting keys end up generating the same end hash.
      if(hashToKey.containsKey(hash)) {
//        System.out.println("Collided - " + hashToKey.get(hash) + ":" + hash +
//            " and " + key + ":" + hash);
        collisions++;
      } else {
        keyToHash.put(key, hash);
        hashToKey.put(hash, key);
        num--;
      }
    }

    System.out.println("Collisions: " + collisions);
  }

  /**
   * Reduce then hash, <code>n</code> times.
   * @param initialHash Starting hash value
   * @param n Number of times to hash, reduce
   * @return Hash in byte[] form that is 'n' steps from 'initialHash'
   */
  protected byte[] hashReduceStep(byte[] initialHash, int n) {
    return hashReduceStep(initialHash, n, chainLength, keyLength);
  }
  /**
   * Reduce then hash, <code>n</code> times. Static version.
   * @param initialHash Starting hash value
   * @param n Number of times to hash, reduce
   * @param cl Chain length
   * @param kl Key length
   * @return Hash in byte[] form that is 'n' steps from 'initialHash'
   */
  protected static byte[] hashReduceStep(byte[] initialHash, int n, int cl, int kl) {
    if (n > cl - 1) {
      System.out.println("Trying to hash/reduce off chain");
      System.exit(-1);
    }
    int chainIndex = cl - n - 1; // Current place in the chain
    byte[] hash = initialHash; // Holds hash that's ultimately returned
    for (int i = 0; i < n; i++) {
      hash = createShaHash(Table.hashReduce(hash, chainIndex, kl));
      chainIndex++;
    }

    return hash;
  }

  /**
   * Randomly generates one key according to parameters in <code>Config</code> object,
   * provided at construction.
   * @see Config
   * @return String adhering to key space constraints
   */
  protected String generateKey() {
    String builtString; // Holds the key as it's built

    // Loop on the key building process until a key in generated that doesn't
    // match an existing key.
    do {
      builtString = "";
      for (int i = 0; i < keyLength; i++) {
        builtString +=
            ALLOWABLE_CHARS[ThreadLocalRandom.current().nextInt(0, ALLOWABLE_CHARS.length)];
      }

    } while (keyToHash.containsKey(builtString));

    return builtString;
  }

  /**
   * Hash reduction algorithm. Produces different results depending on supplied <code>salt</code>.
   * @param hash Hash in byte[] form
   * @param salt int that acts as modifier to method's output
   * @return Plain-text key
   */
  protected String hashReduce(byte[] hash, int salt) {
    return Table.hashReduce(hash, salt, keyLength);
  }

  /**
   * Hash reduction algorithm. Produces different results depending on supplied <code>salt</code>.
   * Static version.
   * @param hash Hash in byte[] form
   * @param salt int that acts as modifier to method's output
   * @param kl Key length
   * @return Plain-text key
   */
  protected static String hashReduce(byte[] hash, int salt, int kl) {
    String reducedKey = ""; // String we produce from hash

    // So a salt of 26 doesn't have two sets of hashReduce functions on an allowable
    // character set of 52.
    if(salt >= ALLOWABLE_CHARS.length) {
      salt += salt%ALLOWABLE_CHARS.length+1;
    }

    // TODO: Different implementation.
    // Slower than the one below, doesn't seem to generate as many matching
    // keys somehow? I like it because it seems cleaner. Will come back to.
    // BigInteger hashAsInt = new BigInteger(hash, 16);
    // BigInteger keySpaceBI = new BigInteger(Long.toString(keySpace));
    // long hashMod = hashAsInt.mod(keySpaceBI).longValue();

    // for(int i = 0; i < kl; i++) {
    // 	long divisor = (long)Math.pow(ALLOWABLE_CHARS.length, i);
    // 	long modDividend = (long)(hashMod/divisor)+salt;
    // 	reducedKey += ALLOWABLE_CHARS[(int)(modDividend%ALLOWABLE_CHARS.length)];
    // }
    // System.out.println(reducedKey);

    /* The length of the hash is divided by 'kl', and stored in 'chunks'.
     * The remainder is stored in 'extra'.
     * The characters of the hash are divided evenly among "'chunks' number"
     * of bins, with 1 character from 'extra' added to each bin until none remain.
     * Each bin is converted to integers from their hex values, 'salt' is added,
     * then modular arithmetic used to take the new integer and turn it into a
     * character appropriate for the keyspace.
     */

//    int chunks = hash.length() / kl; // Integer division
    int chunks = hash.length / kl;
    int extra = hash.length % chunks;
//    int extra = hash.length() % chunks; // Amount left over from above division

    // If the key length is too short, the chunk sizes will be very large,
    // and the conversion process of hex -> dec will overflow.
    try {
      // Loop through the number of spots in a key
      int strStart; // Start bound of hash substring
      int strEnd = 0; // End bound of hash substring
      for (int i = 0; i < kl; i++) {
        strStart = strEnd;
        if (extra > 0) {
          // Include one extra character
          strEnd = strStart + chunks + 1;
          extra--;
        } else {
          strEnd = strStart + chunks;
        }
        // Add one character to 'reducedKey'
//        reducedKey += ALLOWABLE_CHARS[
//            (int)
//                ((Long.parseLong(hash.substring(strStart, strEnd), 16) + salt)
//                    % ALLOWABLE_CHARS.length)];
        byte subByte = 0;
        for(int k = strStart; k < strEnd; k++) {
          subByte ^= hash[k];
        }
        reducedKey += ALLOWABLE_CHARS[((subByte&0xff) + salt) % ALLOWABLE_CHARS.length];
      }
    } catch (NumberFormatException e) {
      System.out.println("Choose a longer key length.");
      System.exit(-1);
    }

    return reducedKey;
  }

  /**
   * Performs basic checks that supplied hash is valid.
   * @param hash Supplied hash in byte[] form
   * @return Validity of hash
   */
  protected static boolean isValidHash(String hash) {
    // Is the length equal to 'HASHLEN'? Is it proper hexadecimal?
    // TODO: Is inserting HASHLEN this way cool?
    return hash.matches("^[a-f0-9]{" + HASHLEN + "}");
  }

  /**
   * Hash, reduce, n times, along a chain that starts with <code>initialKey</code>.
   * @param initialKey Initial plain-text key
   * @param n Number of times to hash, reduce
   * @return Result of 'n' hash, reduce steps
   */
  protected String keyHashStep(String initialKey, int n) {
    return Table.keyHashStep(initialKey, n, chainLength, keyLength);
  }

  /**
   * Hash, reduce, n times, along a chain that starts with <code>initialKey</code>.
   * Static version.
   * @param initialKey Initial plain-text key
   * @param n Number of times to hash, reduce
   * @param cl Chain length
   * @param kl Key length
   * @return Result of 'n' hash, reduce steps
   */
  protected static String keyHashStep(String initialKey, int n, int cl, int kl) {
    if (n > cl - 1) {
      System.out.println("Trying to reduce/hash off chain");
      System.exit(-1);
    }
    String key = initialKey; // Key that's ultimately returned
    for (int i = 0; i < n; i++) {
      key = Table.hashReduce(createShaHash(key), i, kl);
    }

    return key;
  }

  /**
   * Read in previously computed hash map that matches supplied <code>Config</code> object,
   * if it exists.
   * @return Success or failure
   */
  private boolean loadHashMap() {
    try {
      MessageUnpacker unpacker = MessagePack.newDefaultUnpacker(new FileInputStream(fileName));
      // Load 'keyToHash'
      int mapLength = unpacker.unpackMapHeader();
      for (int i = 0; i < mapLength; i++) {
        keyToHash.put(unpacker.unpackString(), unpacker.readPayload(unpacker.unpackBinaryHeader()));
      }
      // Load 'hashToKey'
      mapLength = unpacker.unpackMapHeader();
      for (int i = 0; i < mapLength; i++) {
        hashToKey.put(unpacker.readPayload(unpacker.unpackBinaryHeader()), unpacker.unpackString());
      }
    } catch (IOException e) {
      // The file doesn't exist
      return false;
    }
    return true;
  }

  /**
   * Serialize rainbow table represented by 'hashToKey' and 'keyToHash', write to disk.
   * @see MessagePack
   * @see MessagePacker
   */
  private void writeHashMap() {
    try {
      MessagePacker packer = MessagePack.newDefaultPacker(new FileOutputStream(fileName));

      // keyToHash
      packer.packMapHeader(keyToHash.size());
      for (Map.Entry<String, byte[]> entry : keyToHash.entrySet()) {
        packer.packString(entry.getKey());
        packer.packBinaryHeader(entry.getValue().length);
        packer.writePayload(entry.getValue());
      }
      // hashToKey
      packer.packMapHeader(hashToKey.size());
      for (Map.Entry<byte[], String> entry : hashToKey.entrySet()) {
        packer.packBinaryHeader(entry.getKey().length);
        packer.writePayload(entry.getKey());
        packer.packString(entry.getValue());
      }
      packer.close();
    } catch (Exception e) {
      // We can continue, but their table is lost after program termination
      System.out.println("Error writing to disk.");
      e.printStackTrace();
    }
  }
}